### ISSUE TITLE
unneccessary check for pool_grp/svcl being NULL in H5daos_init (breaks examples)

### ISSUE THREAD

**Issue by christgau** [HDFGroup/vol-daos#1]
Hi, 

in H5daos_init there are checks that the DAOS pool and SVCL aren't NULL. However, this appears to be inconsistent with that the connector is actually able to accept: https://github.com/HDFGroup/vol-daos/blob/95772a5c1134ebf671483c08a0f5d3ef1aafb69e/src/daos_vol.c#L384-L387

A little bit later, the (unmodified, since const) values of pool_grp and pool_svcl arguments are passed to `H5_daos_set_pool_globals`: https://github.com/HDFGroup/vol-daos/blob/95772a5c1134ebf671483c08a0f5d3ef1aafb69e/src/daos_vol.c#L405

However, `H5_daos_set_pool_globals` accepts the two parameters being NULL and the function uses the default values or values passed via environment variables in that case, which is quiet convenient. 

The issue in H5daos_init actually breaks allmost if not all of the examples which initalize the group to NULL: https://github.com/HDFGroup/vol-daos/blob/95772a5c1134ebf671483c08a0f5d3ef1aafb69e/examples/h5dsm_file_open.c#L5

One ends up with an error like this:
```
DAOS VOL-DIAG: Error detected in DAOS VOL (1.0.0) MPI-process 0:
  #000: /home/centos/install/hdf5/vol-daos/src/daos_vol.c line 385 in H5daos_init(): not a valid service group
    major: Invalid arguments to routine
    minor: Bad value
*FAILED*
        at h5dsm_file_open.c:21 in main()...
```

I suggest to remove the checks mentioned above as the NULL values are actually accepted by the routine they are passed to.

**Comment by jhendersonHDF** [comment]
Thanks for reporting this! As you noticed, there were indeed some changes to the way that the pool group name and pool service list were handled which allowed NULL internally so that they could be picked up from environment variables if set. Those changes hadn't made it to the public interface yet, but should be address by #18.
