### ISSUE TITLE
Using vol connector via environment variable without application modifications

### ISSUE THREAD

**Issue by christgau** [HDFGroup/vol-daos#2]
Hi there,

I'm trying to figure out how the VOL connector can be used for existing HDF5 applications. According to the User's Guide using the environment variable approach looks best for this use case:

> The environment variable is useful when the application either cannot or does not need to be modified to use
DAOS storage (e.g., the application makes no native-specific HDF5 API calls). It is also the easiest to use as
it requires very little setup and no changes to the application’s source code.

From my understanding, very simple applications should not need any modification. Thus, I tried to run the [h5_write example from the HDF5 main repository](https://github.com/HDFGroup/hdf5/blob/b947f7e911e498f5455a78836a6f82a042dd5b33/examples/h5_write.c) which I compiled using `h5pcc`. Following the VOL User's Guide, I set the `HDF5_VOL_CONNECTOR=daos` and `HDF5_PLUGIN_PATH` to the library path and run the binary but it fails:

```
# starting it with mpiexec or not doesn't make a difference here.
$ mpiexec -n 1 ./h5_write
HDF5-DIAG: Error detected in HDF5 (1.12.1-3) MPI-process 0:
  #000: H5T.c line 1886 in H5Tcopy(): obj_id is not a datatype ID
    major: Invalid arguments to routine
    minor: Inappropriate type
DAOS VOL-DIAG: Error detected in DAOS VOL (1.0.0) MPI-process 0:
  #000: /home/centos/install/hdf5/vol-daos/src/daos_vol_dset.c line 559 in H5_daos_dataset_create(): dataset create failed in task "default (probably operation setup)": error during operation setup (H5_DAOS_SETUP_ERROR)
    major: Dataset
    minor: Can't operate on object
  #001: /home/centos/install/hdf5/vol-daos/src/daos_vol.c line 3287 in H5_daos_h5op_finalize(): operation "dataset create" failed in task "default (probably operation setup)": error during operation setup (H5_DAOS_SETUP_ERROR)
    major: Low-level I/O
    minor: Unable to initialize object
  #002: /home/centos/install/hdf5/vol-daos/src/daos_vol_dset.c line 492 in H5_daos_dataset_create(): can't create dataset
    major: Dataset
    minor: Unable to initialize object
  #003: /home/centos/install/hdf5/vol-daos/src/daos_vol_dset.c line 641 in H5_daos_dataset_create_helper(): failed to copy datatype
    major: Dataset
    minor: Unable to copy object
HDF5-DIAG: Error detected in HDF5 (1.12.1-3) MPI-process 0:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5VLcallback.c line 1793 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1758 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
```

The "file" itself is created in the DAOS pool as well as the root group within the file/container. I confirmed that with h5dump. However, the dataset creation fails as shown above. I can fix the example by adding calls to `H5Pcreate`, `H5Pset_fapl_daos`, and `H5Pset_all_coll_metadata_ops` as shown in the User's Guide and link against the vol connector. This, however, appears not to be the intention behind the environment variable approach. 

I also tried the `ph5_example` but without any modifications. Again, the application crashes:
```
# mpiexec -n 2 ./ph5_example
Parallel test files are:
   ./ParaEg0.h5
   ./ParaEg1.h5
--------------------------------
Proc 0: --------------------------------
Proc 1: *** testing PHDF5 dataset using split communicators...
--------------------------------
Independent write test on file ./ParaEg0.h5 ./ParaEg1.h5
*** testing PHDF5 dataset using split communicators...
--------------------------------
Independent write test on file ./ParaEg0.h5 ./ParaEg1.h5
--------------------------------
Proc 1: *** testing PHDF5 dataset independent write...
--------------------------------
Independent write test on file ./ParaEg0.h5
H5Pcreate access succeed
HDF5-DIAG: Error detected in HDF5 (1.12.1-3) MPI-process 0:
  #000: H5P.c line 105 in H5Pcopy(): property object doesn't exist
    major: Property lists
    minor: Object not found
DAOS VOL-DIAG: Error detected in DAOS VOL (1.0.0) MPI-process 0:
  #000: /home/centos/install/hdf5/vol-daos/src/daos_vol_file.c line 835 in H5_daos_file_create(): failed to copy fapl
    major: File accessibility
    minor: Unable to copy object
HDF5-DIAG: Error detected in HDF5 (1.12.1-3) MPI-process 0:
  #000: H5F.c line 539 in H5Fcreate(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3269 in H5VL_file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 3235 in H5VL__file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
ph5example: ph5example.c:877: test_split_comm_access: Assertion `fid != -1' failed.
```

Based on these two examples, I am not sure which restrictions or requirements apply to an HDF5 application that should be run with the DAOS VOL connector. At the moment it appears that using the connector via the environment variable does not appear to work with (too) simple applications. The examples from the connector all make the H5P calls mentioned above and require them to be linked with the connector. This applies to most of the DAOS VOL tests as well. Thus, the environment variables are not required for them to work. 

I wonder if this is a mismatch between the implementation and the documentation. Nevertheless; it would be great if an example could be provided that contains a minimal application which makes use the environment variable approach.

**Comment by mchaarawi** [comment]
i just tried the h5_write.c example with the same steps that you described and it worked fine for me.
the only thought i have here is that you might be missing -shlib option.
so to build, try something like:
h5pcc -shlib h5_write.c -o h5_write

**Comment by christgau** [comment]
> the only thought i have here is that you might be missing -shlib option.

Thanks for pointing this out. It did the trick and I was able to run the h5_write example without problems after recompiling the code of the example with the `-shlib`.
