### ISSUE TITLE
Defining installation paths

### ISSUE THREAD

**Issue by brianjmurrell** [HDFGroup/vol-daos#41]
I'm not very familiar with cmake (much more so with GNU Autotools), so if the answer to my question is buried in there somewhere, please forgive me.

Can I define the path where the libraries, pkg-config files, etc. are installed?  They seem to want to go into `/usr/lib` by default but I'm not finding the knob to make them install somewhere else.

**Comment by jhendersonHDF** [comment]
Hi @brianjmurrell,

with CMake, you typically would set CMake's `CMAKE_INSTALL_PREFIX` [variable](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) as in:

```bash
cmake -DCMAKE_INSTALL_PREFIX=/my/install/path ..
```

when building the connector. This would install things under `/my/install/path/lib`, `/my/install/path/bin`, etc.

Common CMake options to set when building the connector are listed in the "Installation" section of the README, but, as currently written, it might not be very clear how they should be used.

**Comment by brianjmurrell** [comment]
Wouldn't `CMAKE_INSTALL_PREFIX` be the overall prefix, as in `/usr/` or (`/usr/local`) on an FSSTD compliant system, with binaries going into  `CMAKE_INSTALL_PREFIX/bin/` (usually referred to as `bindir`) and libraries going into  `CMAKE_INSTALL_PREFIX/lib64/` (usually called `libdir`) (on RH/SUSE based systems) or  `CMAKE_INSTALL_PREFIX/lib/x86_64-linux-gnu/` (on Debian/Ubuntu based systems)?

What I am looking for is variables to define `bindir` and `libdir`, etc., such as https://github.com/HDFGroup/hdf5/ has.

**Comment by jhendersonHDF** [comment]
Ah ok, in that case you'd probably be looking for the `HDF5_VOL_DAOS_INSTALL_BIN_DIR`, `HDF5_VOL_DAOS_INSTALL_LIB_DIR`, `HDF5_VOL_DAOS_INSTALL_INCLUDE_DIR` and `HDF5_VOL_DAOS_INSTALL_DATA_DIR` (the `share` directory) CMake variables that the project checks for. I see that those aren't documented in the README; I'll make a note to do that.

**Comment by brianjmurrell** [comment]
Yes, this is exactly what I was looking for.  Thank you so much!

I just need to become more proficient and being able to find these sorts of things in CMake based build systems.
